server:
  port : 0

spring:
  application:
    name: auth
  main:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: senha
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    format-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

app.jwtSecret: p3O5mFjPhs
app.jwtExpirationMs: 3600
